set(COMMUNICATION_DIR  ${KOURETES_DIR}/src/communication/)
set(NARUKOM_DIR  ${KOURETES_DIR}/src/narukom/)
set(MOTION_DIR  ${KOURETES_DIR}/src/motion/)
set(BEHAVIOR_DIR  ${KOURETES_DIR}/src/behavior/)
set(LOCALIZATION_DIR  ${KOURETES_DIR}/src/localization/)
set(SENSORS_DIR  ${KOURETES_DIR}/src/sensors/)
set(VISION_DIR  ${KOURETES_DIR}/src/vision/)
set(EXTERNAL_DIR ${KOURETES_DIR}/external)
